# Generated by Django 4.2 on 2023-06-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_alter_produkitem_kategori_alter_produkitem_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('PW', 'Semua'), ('P', 'Pria'), ('W', 'Wanita')], max_length=2),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='label',
            field=models.CharField(choices=[('NEW', 'New'), ('SALE', 'Sale'), ('BEST', 'Best')], max_length=4),
        ),
    ]
