# Generated by Django 4.2 on 2023-06-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_contact_alter_produkitem_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('A', 'All'), ('P', 'Pria'), ('W', 'Wanita')], max_length=2),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='label',
            field=models.CharField(choices=[('NEW', 'New'), ('SALE', 'Sale'), ('DISKON', 'Diskon')], max_length=4),
        ),
    ]
